name: example-basic
on:
  push:
    branches:
      - 'main'
  pull_request:
jobs:
  basic-ubuntu-18-v10:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Cypress tests
          # normally you would write
          # uses: cypress-io/github-action@v2
          uses: ./
          # the parameters below are only necessary
          # because we are running these examples in a monorepo
          with:
            working-directory: test-cypress2/
            # just for full picture after installing Cypress
            # print information about detected browsers, etc
            # see https://on.cypress.io/command-line#cypress-info
            build: npx cypress info
